### PR TITLE
Add integration tests for 200 OK for excluded countries

### LINKED ISSUE #293: Add integration tests for 200 OK for excluded regions
Contile v1.4.0 contains a workaround that if enabled (it's on by default) returns a 200 OK with an empty tiles array in the response content for excluded countries instead of 204 No Content.

Add integration tests that verify this new behavior on the integration level if switched on as well as switched off to make sure we can easily disable the workaround later on, if necessary.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1274)

### PR DESCRIPTION
**Pull request by hackebrot**
## Description

This pull request adds two new integration tests for the `excluded_countries_200` functionality of #290.

## Testing

Verify that the two new integration tests run and pass on CI.

## Issue(s)

Resolve #293

### CODE REVIEW

**Review by ashrivastava-qa — COMMENTED** [review]
I didn't clearly understand the reason for adding changes to the `scenarios.yml` file **AND** creating a new `scenarios_204.yml` file? Wouldn't it have worked with just the changes to the scenarios.yml file?

**Comment by hackebrot** [comment]
> I didn't clearly understand the reason for adding changes to the `scenarios.yml` file **AND** creating a new `scenarios_204.yml` file? Wouldn't it have worked with just the changes to the `scenarios.yml `file?

The new `scenarios_204.yml` is used for the new integration test running against a Contile service that has `CONTILE_EXCLUDED_COUNTRIES_200` disabled. This is necessary to have integration test coverage with the workaround enabled and disabled (see [new step in CI job](https://github.com/mozilla-services/contile/pull/294/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R220)).

**Review by ashrivastava-qa — APPROVED** [review]
okay! Got it 👍 Thank you @hackebrot!

**Review by pjenvey — APPROVED** [review]
thanks @hackebrot!

**Comment by hackebrot** [comment]
Thanks for the reviews, team! 🚀

**Pull request merged**
