### PR TITLE
[DISCO-2319] Add code coverage check job and report test results in CI

### PR DESCRIPTION
**Pull request by Trinaa**
## References

JIRA: [DISCO-2319](https://mozilla-hub.atlassian.net/browse/DISCO-2319)
GitHub: N/A

## Description

- Expand the CI `test` job to support CircleCI Test Insights and check for code coverage regressions
    - `report-test-results` formats test results into JUnit XML form for compatibility with CircleCI [Test Insights](https://app.circleci.com/insights/github/mozilla-services/contile/workflows/build-deploy/tests?branch=disco-2319)
    - `run-code-coverage` prevents code coverage regressions by checking for a minimum line coverage of 54% (the current coverage)

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [x] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/contile/blob/main/CONTRIBUTING.md)
- [x] This PR conforms to the [Opsec policies](https://github.com/mozilla-services/websec-check)
- [x] [Functional and performance test](https://github.com/mozilla-services/contile/tree/main/test-engineering) coverage has been expanded and maintained (if applicable)
- [x] Documentation has been updated
- [x] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title

[DISCO-2319]: https://mozilla-hub.atlassian.net/browse/DISCO-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ncloudioj** [comment]
To minimize the development friction, I am leaning towards not enforcing the minimal test coverage in CI for Contile until we have a better understanding of the related tooling as well as how feasible we can achieve the desired coverage. That said, what do you think about establishing coverage observability first in CI by leveraging services like [Codecov](https://about.codecov.io/language/rust/)? In the meantime, I think we can also explore other coverage tools such as Tarpaulin, Kcov, and Grcov to see if they offer better integration options with our CI.

**Comment by ncloudioj** [comment]
Re: [cargo2junit](https://github.com/johnterickson/cargo2junit) and CircleCI Test Insights, do we need junit flavored test outputs for the Test Insights feature? If so, yes, I think we can give it a try.

**Comment by mtbottle** [comment]
> To minimize the development friction, I am leaning towards not enforcing the minimal test coverage in CI for Contile until we have a better understanding of the related tooling as well as how feasible we can achieve the desired coverage goal.

What do you think about starting with a lower limit (like 55%)? I would like to have some system to prevent us from significantly lowering the test coverage, and having a CI blocker feels like the best way to enforce this. Also, if we are finding it too stringent, this value can be tuned (so nothing is permanent).

**Comment by Trinaa** [comment]
> > To minimize the development friction, I am leaning towards not enforcing the minimal test coverage in CI for Contile until we have a better understanding of the related tooling as well as how feasible we can achieve the desired coverage goal. 

> What do you think about starting with a lower limit (like 55%)? I would like to have some system to prevent us from significantly lowering the test coverage, and having a CI blocker feels like the best way to enforce this. Also, if we are finding it too stringent, this value can be tuned (so nothing is permanent).

I feel the same way as Michelle. In Merino having the minimum code coverage check has proven to be a powerful accountability tool. The minimum is currently set at 54%, our current level, and can always be changed. I think it's important to have a conversation if it should lower.

>That said, what do you think about establishing coverage observability first in CI by leveraging services like [Codecov](https://about.codecov.io/language/rust/)? In the meantime, I think we can also explore other coverage tools such as Tarpaulin, Kcov, and Grcov to see if they offer better integration options with our CI.

The current framework `llvm-cov` can produce the Codecov report if we would like to leverage that tool, it also produces an HTML report that we can [immediately observe in CircleCI](https://output.circle-artifacts.com/output/job/a3a3b97c-67f8-40b8-a039-0bfacd44d25c/artifacts/0/target/llvm-cov/html/index.html) (let me know if you'd like to keep the HTML report in CI). I have not used Codecov, so I'm not sure if it's an offering that would benefit us, but my instinct is with 46% of code uncovered, we have plenty of insight on ground that needs covering.

> Re: [cargo2junit](https://github.com/johnterickson/cargo2junit) and CircleCI Test Insights, do we need junit flavored test outputs for the Test Insights feature? If so, yes, I think we can give it a try.

Yes. CircleCI requires this format.

**Comment by pjenvey** [comment]
I agree with Nan's concerns/points and we all agree strict coverage isn't as critical for Rust, but I'm ok with trying out the enforcement (for now), I think we can learn as we go with it. That new PR could be a legitimate case for lowering the 54%.

I lean this way because we're now on the rapid release workflow which suggests we improve overall test coverage and its monitoring. It's a tradeoff: landing changes in prod rapidly probably should add more dev friction to ensure the code quality is there, I'd say especially so in this early phase of its usage as we're figuring it out (maybe let's bump every contile issue's story points by at least +1).

I'll also note we don't monitor code coverage against the contract tests (nor does merino). This would be nice to have but I think it'd be too painful to make work within a Dockerized contile.

**Comment by Trinaa** [comment]
> Using the current coverage as the minimal basically means that all future PRs shall not regress it. Quite frankly, my hunch is that I will likely hit that regression soon with my next PR. Sure, we can always adjust it if necessary, but I don't think we have gathered enough inputs to set a reasonable minimal coverage for this project. Before we do that, I'd like us to better understand:
>- What those uncovered code paths & modules are?
>- Any particular reason they're not being tested?
>- Are there any cases where we can rely on the Rust compiler to enforce certain invariants that would otherwise require manual testing in other languages?

@ncloudioj It seems that's a legitimate case to lower the coverage and I would suggest to do that in the PR. It brings better visibility of the impact of the change to the reviewer(s) and it might inspire them to ask questions or make suggestions. 

> I'll also note we don't monitor code coverage against the contract tests (nor does merino). This would be nice to have but I think it might be too painful to make work within a Dockerized contile.

Contract tests are black-box and my understanding is that line and branch coverage are not appropriate measures of efficacy at that level. You'll traverse many points in the decision tree with this kind of test, but you don't have the granular insight to verify the correctness.

**Review by ncloudioj — APPROVED** [review]
Alrighty, I am sold. Thank you so much for all the insightful points! Let's give it a spin.

**Review by ncloudioj — APPROVED** [review]

**Pull request merged**
