### PR TITLE
Upgrade contile-integration-tests Docker images 🤖

### PR DESCRIPTION
**Pull request by hackebrot**
See https://github.com/mozilla-services/contile-integration-tests/releases/tag/22.1.0

- test: upgrade the Docker images for contile-integration-tests to 22.1.0
- test: add accepted form-factors for partner API endpoints

### CODE REVIEW

**Comment by hackebrot** [comment]
This pull request enables us to run integration tests for https://github.com/mozilla-services/contile/pull/346.

**Review by pjenvey — DISMISSED** [review]
Does #346 need to land first (for the failing integration test to pass)?

**Comment by hackebrot** [comment]
> Does #346 need to land first (for the failing integration test to pass)?

No, I set the environment variables for the partner API to accept all form-factors for now. We can update that on #346 if we want to have these additional checks. 🤖 

I missed to update the partner endpoint URL for Contile now that the partner API   runs `/tilesp/desktop` and `/tilesp/mobile` instead of just `/tilesp`. That should be fixed by 9f3670d.

@jrconlin pointed out to me that the `checks` CI job also failed because failing Rust Core checks unrelated to the integration tests.

**Comment by hackebrot** [comment]
Looks like all checks are now passing after merging the `cargo update` commit from #352. 🚀

**Review by pjenvey — APPROVED** [review]

**Pull request merged**
