### PR TITLE
Rename Contile integration tests to contract tests

### PR DESCRIPTION
**Pull request by Trinaa**
## Description

This pull request renames the integration-tests directory to contract-tests and updates references in the documentation and CI configuration. 

This change clarifies the test suite purpose and distinguishes the suite from the more internal Rust based integration tests.

## Issue(s)
[CONSVC-1784](https://mozilla-hub.atlassian.net/browse/CONSVC-1784)

### CODE REVIEW

**Comment by ncloudioj** [comment]
Hey @Trinaa, so #394 is now closed. A rebase should green your PR.

**Review by pjenvey — APPROVED** [review]

**Review by hackebrot — DISMISSED** [review]
Hi @Trinaa! 👋🏻 

Great work! Your changes LGTM. 🚀

**Comment by hackebrot** [comment]
Merging is currently blocked because we require all commits on Contile to be signed.

There's a GitHub docs page on GPG signing at https://docs.github.com/articles/about-gpg/.

**Comment by Trinaa** [comment]
> 

@hackebrot I seemed to have fallen into a [pitfall](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-rebase-and-merge)

I'm not sure if forcing signature verification is correct/allowed

**Comment by hackebrot** [comment]
Hi @Trinaa! 👋🏻 

My bad. I wasn't aware of this when I suggested you rebase using the GitHub web UI.

I recommend you rebase your local commits to the latest `origin/main` and force-push your branch.

**Comment by Trinaa** [comment]
Resolved by https://github.com/mozilla-services/contile/pull/391

**Pull request merged**
