### PR TITLE
fix: re-add location_test_header support

### LINKED ISSUE #257: Respect location_test_header w/ maxmind enabled
With maxmind enabled, we skip reading the test location header. When enabled the test location header should trump all other providers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1203)

### PR DESCRIPTION
**Pull request by pjenvey**
## Description

via its own location provider, checked before maxmind

(draft for now in case it conflicts w/ #235)

## Testing

New tests pass

## Issue(s)

Closes #257

### CODE REVIEW

**Review by jrconlin — DISMISSED** [review]
I do wonder if we should put this behind either a feature flag or a setting so that it's only enabled for load testing configurations. I don't think it's a huge threat, but someone could screw with things by adding their own `X-Test-Location` header to calls. (Maybe we flag these as "testing" and don't count them?)

**Comment by pjenvey** [comment]
> I do wonder if we should put this behind either a feature flag or a setting so that it's only enabled for load testing configurations.

It is conditional behind the same `test_location_header` setting as it was before

**Comment by pjenvey** [comment]
Moving out of draft as I don't think it conflicts much at all w/ #235

**Review by jrconlin — APPROVED** [review]
?? wonder why that didn't transfer?

**Comment by pjenvey** [comment]
> ?? wonder why that didn't transfer?

Manually merged it for conflicts and added another commit on top of that

**Pull request merged**
