### PR TITLE
test: replace contract test sequence diagram with Miro version

### PR DESCRIPTION
**Pull request by Trinaa**
## Description

Update sequence diagram in contract-tests README to [Miro version](https://miro.com/app/board/uXjVOkw1f-s=/). 

## Issue(s)
[CONSVC-1896](https://mozilla-hub.atlassian.net/browse/CONSVC-1896)

### CODE REVIEW

**Review by pjenvey — DISMISSED** [review]

**Review by hackebrot — CHANGES_REQUESTED** [review]
Hi @Trinaa! 👋🏻 

We have added new fields to the cache audience key since I created the original. Do you mind updating that information?

See https://github.com/mozilla-services/contile/blob/bd526568cccae1ce42890e3c7c7691b83e3b80d1/src/server/cache.rs#L22-L35

**Review by pjenvey — DISMISSED** [review]

**Comment by Trinaa** [comment]
Hi @hackebrot,

- added the new fields to cache audience key
- homogenized the arrow styles (a mix might have contributed to the crookedness)
- adjusted arrow labels and reduced white space
- bolded the 'scenarios.yml' and 'responses.yml' in file comments

**Review by hackebrot — CHANGES_REQUESTED** [review]
Hi @Trinaa! 👋🏻 

This is looking much better! Thank you.

Two minor corrections:
* The note on the left reads `verify the responses from contile`. Now that the diagram also shows an request from `client` to `partner`, should this be `verify the responses from contile or partner`?
* The description for a `204` HTTP response status is `No Content`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

**Review by hackebrot — APPROVED** [review]
LGTM! ✏️

**Pull request merged**
